#!/usr/bin/env python

import os
import sys

#define paths
#--------------------------------------------

mpath = os.getcwd()

def usage():
     print
     print 'Usage: '+ sys.argv[0]+ ' <current release> + < comparison release > + < TauID product > + < Number of prongs >'
     print 'e.g.: ' + sys.argv[0]+ ' CMSSW_2_2_0_pre1 CMSSW_2_1_10 pftau HadronicTauOneAndThreeProng '
     print 
     return 0
   
if __name__ == "__main__":

   currentrelease = ""
   comparisonrelease = ""
   tauidproduct = ""
   numberofprongs = ""
   
   if len(sys.argv)==1 or len(sys.argv) == 2 or len(sys.argv) == 3 or len(sys.argv) == 4 or len(sys.argv)>6:
	   usage()
	   sys.exit()
   if len(sys.argv)==5:
        try:
            currentrelease = sys.argv[1]
            comparisonrelease = sys.argv[2]
            tauidproduct = sys.argv[3]
            numberofprongs = sys.argv[4]            
        except ValueError:
            usage()
            sys.exit()

   
   outputfilelog = sys.argv[0].replace(".py",".log")
   outputfilelog = outputfilelog.replace("./","")

   print  tauidproduct  + " " + currentrelease + " " + numberofprongs + " " + comparisonrelease
   print 
   
   outputwebpage = tauidproduct + "_" + currentrelease + "_" + numberofprongs + ".html"
   
   print outputwebpage
   
   try:
    outputfile = open(outputwebpage, "w") 
#	print "Output html file is being written" 
   except IOError:
	print " error opening " + outputwebpage
	sys.exit()
   outputfile.write('''<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd"><html>\n''') 
   outputfile.write('''<head><title>CMSSW Release Validation</title>\n''')
   outputfile.write('''    <link rel="stylesheet" type="text/css" media="print" href="../css/print.css">\n''')
   outputfile.write('''    <style type="text/css" media="screen">\n''')
   outputfile.write('''    @import url("../css/layout.css");\n''')
   outputfile.write('''    @import url("../css/content.css");\n''')
   outputfile.write('''    @import url("../css/docbook.css");\n''')
   outputfile.write('''    </style>\n''')
   outputfile.write('''    <meta name="MSSmartTagsPreventParsing" content="TRUE">\n''')
   outputfile.write('''</head>\n\n''')
   outputfile.write('''<body>\n''')

   outputfile.write('''<div id="fedora-header"><!-- DIV_I -->\n''')
   outputfile.write('''   <div id="fedora-header-logo">\n''')
   outputfile.write('''      <strong><big>CMSSW Release Validation</big></strong>\n''')
   outputfile.write('''      <br>\n''')
   outputfile.write('''      <div align="right"><a href="mailto:ricardo@fnal.gov">ricardo@fnal.gov</a></div>\n''')
   outputfile.write('''   </div>\n''')
   outputfile.write('''   <div id="fedora-header-items">\n''')
   outputfile.write('''      <span class="fedora-header-icon">\n''')
   outputfile.write('''     [<a href="https://twiki.cern.ch/twiki/bin/view/CMS/SWGuideTauCodeValidation" alt="">About this page</a>]<br>\n''')
   outputfile.write('''     <strong><tt class="link-internal"></tt>\n''')					        
   outputfile.write('''     </strong>\n''')
   outputfile.write('''     </span>\n''')
   outputfile.write('''   </div>\n''')
   outputfile.write('''</div><!-- DIV_I -->\n''')
   outputfile.write('''<div id="fedora-nav"></div>\n\n''')

   outputfile.write('''         <div> <!-- DIV-4 -->\n''')
   outputfile.write('''         <br>\n''')       
   outputfile.write('''         <center><strong>Validation plots of ''' + tauidproduct + '''</strong></center>\n''')
   outputfile.write('''         <center><strong>Step by Step Efficiency ''' + comparisonrelease + '''</strong></center>\n''')
   outputfile.write('''         <table border="1" cellpadding="4" align="center">\n''')
   outputfile.write('''         <tbody align="center">\n''')
   outputfile.write('''         <center>\n''')
   outputfile.write('''         <tr>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/TauIdEffStepByStepeta.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/TauIdEffStepByStepeta.png" width="290" border="0" alt="TauIdEffStepByStepeta.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/TauIdEffStepByStepphi.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/TauIdEffStepByStepphi.png" width="290" border="0" alt="TauIdEffStepByStepphi.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/TauIdEffStepBySteppt.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/TauIdEffStepBySteppt.png" width="290" border="0" alt="TauIdEffStepBySteppt.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/TauIdEffStepByStepenergy.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/TauIdEffStepByStepenergy.png" width="290" border="0" alt="TauIdEffStepByStepenergy.png"></a>\n''')
   outputfile.write('''         </tr>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </tbody>\n''')
   outputfile.write('''         </table>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </div><!-- DIV-4 -->\n''')
   outputfile.write('''         <div></div>\n''')
   
   outputfile.write('''         <div> <!-- DIV-4 -->\n''')
   outputfile.write('''         <br>\n''')       
   outputfile.write('''         <center><strong>PFJet Efficiency (matching deltaR less than 0.15 compared to ''' + comparisonrelease + ''')</strong></center>\n''')
   outputfile.write('''         <table border="1" cellpadding="4" align="center">\n''')
   outputfile.write('''         <tbody align="center">\n''')
   outputfile.write('''         <center>\n''')
   outputfile.write('''         <tr>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/PFJetMatchingEffeta.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/PFJetMatchingEffeta.png" width="290" border="0" alt="PFJetMatchingEffeta.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/PFJetMatchingEffphi.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/PFJetMatchingEffphi.png" width="290" border="0" alt="PFJetMatchingEffphi.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/PFJetMatchingEffpt.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/PFJetMatchingEffpt.png" width="290" border="0" alt="PFJetMatchingEffpt.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/PFJetMatchingEffenergy.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/PFJetMatchingEffenergy.png" width="290" border="0" alt="PFJetMatchingEffenergy.png"></a>\n''')
   outputfile.write('''         </tr>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </tbody>\n''')
   outputfile.write('''         </table>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </div><!-- DIV-4 -->\n''')
   outputfile.write('''         <div></div>\n''')

#   outputfile.write('''         <div> <!-- DIV-4 -->\n''')
#   outputfile.write('''         <br>\n''')       
#   outputfile.write('''         <center><strong>Finding Leading Track Efficiency  (compared to ''' + comparisonrelease + '''</strong></center>\n''')
#   outputfile.write('''         <table border="1" cellpadding="4" align="center">\n''')
#   outputfile.write('''         <tbody align="center">\n''')
#   outputfile.write('''         <center>\n''')
#   outputfile.write('''         <tr>\n''')
#   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/LeadingTrackFindingEffeta.png">\n''')
#   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/LeadingTrackFindingEffeta.png" width="290" border="0" alt="LeadingTrackFindingEffeta.png"></a>\n''')
#   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/LeadingTrackFindingEffphi.png">\n''')
#   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/LeadingTrackFindingEffphi.png" width="290" border="0" alt="LeadingTrackFindingEffphi.png"></a>\n''')
#   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/LeadingTrackFindingEffpt.png">\n''')
#   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/LeadingTrackFindingEffpt.png" width="290" border="0" alt="LeadingTrackFindingEffpt.png"></a>\n''')
#   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/LeadingTrackFindingEffenergy.png">\n''')
#   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/LeadingTrackFindingEffenergy.png" width="290" border="0" alt="LeadingTrackFindingEffenergy.png"></a>\n''')
#   outputfile.write('''         </tr>\n''')
#   outputfile.write('''         </center>\n''')
#   outputfile.write('''         </tbody>\n''')
#   outputfile.write('''         </table>\n''')
#   outputfile.write('''         </center>\n''')
#   outputfile.write('''         </div><!-- DIV-4 -->\n''')
#   outputfile.write('''         <div></div>\n''')

   outputfile.write('''         <div> <!-- DIV-4 -->\n''')
   outputfile.write('''         <br>\n''')       
   outputfile.write('''         <center><strong>Leading Track Pt Efficiency (compared to ''' + comparisonrelease + '''</strong></center>\n''')
   outputfile.write('''         <table border="1" cellpadding="4" align="center">\n''')
   outputfile.write('''         <tbody align="center">\n''')
   outputfile.write('''         <center>\n''')
   outputfile.write('''         <tr>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/LeadingTrackPtCutEffeta.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/LeadingTrackPtCutEffeta.png" width="290" border="0" alt="LeadingTrackPtCutEffeta.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/LeadingTrackPtCutEffphi.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/LeadingTrackPtCutEffphi.png" width="290" border="0" alt="LeadingTrackPtCutEffphi.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/LeadingTrackPtCutEffpt.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/LeadingTrackPtCutEffpt.png" width="290" border="0" alt="LeadingTrackPtCutEffpt.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/LeadingTrackPtCutEffenergy.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/LeadingTrackPtCutEffenergy.png" width="290" border="0" alt="LeadingTrackPtCutEffenergy.png"></a>\n''')
   outputfile.write('''         </tr>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </tbody>\n''')
   outputfile.write('''         </table>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </div><!-- DIV-4 -->\n''')
   outputfile.write('''         <div></div>\n''')

   outputfile.write('''         <div> <!-- DIV-4 -->\n''')
   outputfile.write('''         <br>\n''')       
   outputfile.write('''         <center><strong> Isolation (track) Efficiency  (compared to ''' + comparisonrelease + '''</strong></center>\n''')
   outputfile.write('''         <table border="1" cellpadding="4" align="center">\n''')
   outputfile.write('''         <tbody align="center">\n''')
   outputfile.write('''         <center>\n''')
   outputfile.write('''         <tr>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/TrackIsolationEffeta.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/TrackIsolationEffeta.png" width="290" border="0" alt="TrackIsolationEffeta.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/TrackIsolationEffphi.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/TrackIsolationEffphi.png" width="290" border="0" alt="TrackIsolationEffphi.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/TrackIsolationEffpt.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/TrackIsolationEffpt.png" width="290" border="0" alt="TrackIsolationEffpt.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/TrackIsolationEffenergy.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/TrackIsolationEffenergy.png" width="290" border="0" alt="TrackIsolationEffenergy.png"></a>\n''')
   outputfile.write('''         </tr>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </tbody>\n''')
   outputfile.write('''         </table>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </div><!-- DIV-4 -->\n''')
   outputfile.write('''         <div></div>\n''')

   outputfile.write('''         <div> <!-- DIV-4 -->\n''')
   outputfile.write('''         <br>\n''')       
   outputfile.write('''         <center><strong> Isolation (track and ECAL) Efficiency  (compared to ''' + comparisonrelease + '''</strong></center>\n''')
   outputfile.write('''         <table border="1" cellpadding="4" align="center">\n''')
   outputfile.write('''         <tbody align="center">\n''')
   outputfile.write('''         <center>\n''')
   outputfile.write('''         <tr>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/ECALIsolationEffeta.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/ECALIsolationEffeta.png" width="290" border="0" alt="ECALIsolationEffeta.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/ECALIsolationEffphi.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/ECALIsolationEffphi.png" width="290" border="0" alt="ECALIsolationEffphi.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/ECALIsolationEffpt.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/ECALIsolationEffpt.png" width="290" border="0" alt="ECALIsolationEffpt.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/ECALIsolationEffenergy.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/ECALIsolationEffenergy.png" width="290" border="0" alt="ECALIsolationEffenergy.png"></a>\n''')
   outputfile.write('''         </tr>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </tbody>\n''')
   outputfile.write('''         </table>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </div><!-- DIV-4 -->\n''')
   outputfile.write('''         <div></div>\n''')

   outputfile.write('''         <div> <!-- DIV-4 -->\n''')
   outputfile.write('''         <br>\n''')       
   outputfile.write('''         <center><strong>Electron Rejection Efficiency  (compared to ''' + comparisonrelease + '''</strong></center>\n''')
   outputfile.write('''         <table border="1" cellpadding="4" align="center">\n''')
   outputfile.write('''         <tbody align="center">\n''')
   outputfile.write('''         <center>\n''')
   outputfile.write('''         <tr>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/AgainstElectronEffeta.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/AgainstElectronEffeta.png" width="290" border="0" alt="AgainstElectronEffeta.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/AgainstElectronEffphi.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/AgainstElectronEffphi.png" width="290" border="0" alt="AgainstElectronEffphi.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/AgainstElectronEffpt.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/AgainstElectronEffpt.png" width="290" border="0" alt="AgainstElectronEffpt.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/AgainstElectronEffenergy.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/AgainstElectronEffenergy.png" width="290" border="0" alt="AgainstElectronEffenergy.png"></a>\n''')
   outputfile.write('''         </tr>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </tbody>\n''')
   outputfile.write('''         </table>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </div><!-- DIV-4 -->\n''')
   outputfile.write('''         <div></div>\n''')

   outputfile.write('''         <div> <!-- DIV-4 -->\n''')
   outputfile.write('''         <br>\n''')       
   outputfile.write('''         <center><strong>Muon Rejection Efficiency  (compared to ''' + comparisonrelease + '''</strong></center>\n''')
   outputfile.write('''         <table border="1" cellpadding="4" align="center">\n''')
   outputfile.write('''         <tbody align="center">\n''')
   outputfile.write('''         <center>\n''')
   outputfile.write('''         <tr>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/AgainstMuonEffeta.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/AgainstMuonEffeta.png" width="290" border="0" alt="AgainstMuonEffeta.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/AgainstMuonEffphi.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/AgainstMuonEffphi.png" width="290" border="0" alt="AgainstMuonEffphi.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/AgainstMuonEffpt.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/AgainstMuonEffpt.png" width="290" border="0" alt="AgainstMuonEffpt.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tauidproduct + '''/''' + numberofprongs +'''/AgainstMuonEffenergy.png">\n''')
   outputfile.write('''            <img src="''' + tauidproduct + '''/''' + numberofprongs +'''/AgainstMuonEffenergy.png" width="290" border="0" alt="AgainstMuonEffenergy.png"></a>\n''')
   outputfile.write('''         </tr>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </tbody>\n''')
   outputfile.write('''         </table>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </div><!-- DIV-4 -->\n''')
   outputfile.write('''         <div></div>\n''')
   
   outputfile.write('''     </div> <!-- DIV-3 -->\n''')   
   
   outputfile.write('''</div> <!-- DIV-2 -->\n''')
   outputfile.write('''<div class="fedora-coner-br">&nbsp;</div>\n''')
   outputfile.write('''<div class="fedora-coner-bl">&nbsp;</div>\n''')
   outputfile.write('''<!-- content END -->\n\n''')
   outputfile.write('''<!-- footer BEGIN -->\n''')
   outputfile.write('''<div id="fedora-footer">\n''')
   outputfile.write('''Ricardo Vasquez Sierra\n''')
   outputfile.write('''<br>\n''')
   outputfile.write('''Fermilab/UCDavis\n''')
   outputfile.write('''<br>\n''')
   outputfile.write('''</div>\n''')
   outputfile.write('''<!-- footer END -->\n''')
   outputfile.write('''</body></html>\n''')
