#!/usr/bin/python

import os
import sys

#define paths
#--------------------------------------------

mpath = os.getcwd()

def usage():
     print
     print 'Usage: '+ sys.argv[0]+ ' <root file of interest> + <release comparison> '
     print 'e.g.: ' + sys.argv[0]+ ' pftautagHE_CMSSW_1_8_0_pre1_OneProngAndThreeProng_PFTau.root CMSSW_1_7_0_pre5'
     print 
     return 0
   
if __name__ == "__main__":

   rootfile = ""
   comparisonrelease = ""
   if len(sys.argv)==1 or len (sys.argv) == 2 or len(sys.argv)>4:
	   usage()
	   sys.exit()
   if len(sys.argv)==3:
        try:
            rootfile = sys.argv[1]
            comparisonrelease = sys.argv[2]
        except ValueError:
            usage()
            sys.exit()

   
   outputfilelog = sys.argv[0].replace(".py",".log")
   outputfilelog = outputfilelog.replace("./","")

   rootfileparts = rootfile.split("_")
       
   print " root file " + rootfile
   
   print " rootfileparts: "
   
   print rootfileparts
   
   print  len(rootfileparts) 
   
   tagtype = ""
   releaseversion = ""
   prongsanalyzed = ""
   
   tagtype = rootfileparts[0]

   if len(rootfileparts) == 7:
       releaseversion =  rootfileparts[1] + "_" +rootfileparts[2] +"_"+ rootfileparts[3] + "_"+ rootfileparts[4]
       prongsanalyzed = rootfileparts[5]
   if len(rootfileparts) == 8:
       releaseversion =  rootfileparts[1] + "_"+ rootfileparts[2] + "_"+ rootfileparts[3] + "_"+ rootfileparts[4] + "_"+ rootfileparts[5]
       prongsanalyzed = rootfileparts[6]
	   
   print  tagtype  + " " + releaseversion + " " + prongsanalyzed + " " + comparisonrelease
   print 
   
   outputwebpage = tagtype + "_" + releaseversion + "_" + prongsanalyzed + ".html"
   
   print outputwebpage
   try:
    outputfile = open(outputwebpage, "w") 
#	print "Output html file is being written" 
   except IOError:
	print " error opening " + outputwebpage
	sys.exit()
   outputfile.write('''<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd"><html>\n''') 
   outputfile.write('''<head><title>CMSSW Release Validation</title>\n''')
   outputfile.write('''    <link rel="stylesheet" type="text/css" media="print" href="../css/print.css">\n''')
   outputfile.write('''    <style type="text/css" media="screen">\n''')
   outputfile.write('''    @import url("../css/layout.css");\n''')
   outputfile.write('''    @import url("../css/content.css");\n''')
   outputfile.write('''    @import url("../css/docbook.css");\n''')
   outputfile.write('''    </style>\n''')
   outputfile.write('''    <meta name="MSSmartTagsPreventParsing" content="TRUE">\n''')
   outputfile.write('''</head>\n\n''')
   outputfile.write('''<body>\n''')

   outputfile.write('''<div id="fedora-header"><!-- DIV_I -->\n''')
   outputfile.write('''   <div id="fedora-header-logo">\n''')
   outputfile.write('''      <strong><big>CMSSW Release Validation</big></strong>\n''')
   outputfile.write('''      <br>\n''')
   outputfile.write('''      <div align="right"><a href="mailto:ricardo@fnal.gov">ricardo@fnal.gov</a></div>\n''')
   outputfile.write('''   </div>\n''')
   outputfile.write('''   <div id="fedora-header-items">\n''')
   outputfile.write('''      <span class="fedora-header-icon">\n''')
   outputfile.write('''     [<a href="https://twiki.cern.ch/twiki/bin/view/CMS/SWGuideTauCodeValidation" alt="">About this page</a>]<br>\n''')
   outputfile.write('''     <strong><tt class="link-internal"></tt>\n''')					        
   outputfile.write('''     </strong>\n''')
   outputfile.write('''     </span>\n''')
   outputfile.write('''   </div>\n''')
   outputfile.write('''</div><!-- DIV_I -->\n''')
   outputfile.write('''<div id="fedora-nav"></div>\n\n''')

   outputfile.write('''<div class="fedora-corner-tr">&nbsp;</div>\n''')
   outputfile.write('''<div class="fedora-corner-tl">&nbsp;</div>\n''')
   outputfile.write('''<div class="article" lang="en"></div>\n''')
   outputfile.write('''<div class="titlepage"> <!-- DIV-2 -->\n''')
   outputfile.write('''    <div> <!-- DIV-3 -->\n''')
   outputfile.write('''         <div> <!-- DIV-4 -->\n''')
   outputfile.write('''         <br>\n''')
   outputfile.write('''         <center><strong>''' + releaseversion + ''' Collection: '''+ tagtype + '''  ''' + prongsanalyzed + '''</strong></center>\n''')
   outputfile.write('''         <center><strong>Step by Step Efficiencies</strong></center>\n''')
   outputfile.write('''         <table border="1" cellpadding="4" align="center">\n''')
   outputfile.write('''         <tbody align="center">\n''')
   outputfile.write('''         <center>\n''')
   outputfile.write('''         <tr>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/EfficienciesStepByStepEta.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/EfficienciesStepByStepEta.png" width="290" border="0" alt="EfficienciesStepByStepEta.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/EfficienciesStepByStepPhi.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/EfficienciesStepByStepPhi.png" width="290" border="0" alt="EfficienciesStepByStepPhi.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/EfficienciesStepByStepPt.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/EfficienciesStepByStepPt.png" width="290" border="0" alt="EfficienciesStepByStepPt.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/EfficienciesStepByStepEnergy.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/EfficienciesStepByStepEnergy.png" width="290" border="0" alt="EfficienciesStepByStepEnergy.png"></a>\n''')   
   outputfile.write('''         </tr>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </tbody>\n''')
   outputfile.write('''         </table>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </div><!-- DIV-4 -->\n''')
   outputfile.write('''         <div></div>\n''')
   outputfile.write('''         <div> <!-- DIV-4 -->\n''')
   outputfile.write('''         <br>\n''')       
   outputfile.write('''         <center><strong>PFCandidate Matching Efficiency (matching deltaR less than 0.15 compared to ''' + comparisonrelease + ''' )</strong></center>\n''')
   outputfile.write('''         <table border="1" cellpadding="4" align="center">\n''')
   outputfile.write('''         <tbody align="center">\n''')
   outputfile.write('''         <center>\n''')
   outputfile.write('''         <tr>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/PFTauCandTotalEfficiencyEta.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/PFTauCandTotalEfficiencyEta.png" width="290" border="0" alt="PFTauCandTotalEfficiencyEta.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/PFTauCandTotalEfficiencyPhi.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/PFTauCandTotalEfficiencyPhi.png" width="290" border="0" alt="PFTauCandTotalEfficiencyPhi.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/PFTauCandTotalEfficiencyPt.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/PFTauCandTotalEfficiencyPt.png" width="290" border="0" alt="PFTauCandTotalEfficiencyPt.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/PFTauCandTotalEfficiencyEnergy.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/PFTauCandTotalEfficiencyEnergy.png" width="290" border="0" alt="PFTauCandTotalEfficiencyEnergy.png"></a>\n''')
   outputfile.write('''         </tr>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </tbody>\n''')
   outputfile.write('''         </table>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </div><!-- DIV-4 -->\n''')
   outputfile.write('''         <div></div>\n''')

   outputfile.write('''         <div> <!-- DIV-4 -->\n''')
   outputfile.write('''         <br>\n''')       
   outputfile.write('''         <center><strong>Finding Leading Charged Hadron Efficiency  (compared to ''' + comparisonrelease + ''') </strong></center>\n''')
   outputfile.write('''         <table border="1" cellpadding="4" align="center">\n''')
   outputfile.write('''         <tbody align="center">\n''')
   outputfile.write('''         <center>\n''')
   outputfile.write('''         <tr>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/FindingLeadingChargeHadronEfficiencyEta.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/FindingLeadingChargeHadronEfficiencyEta.png" width="290" border="0" alt="FindingLeadingChargeHadronEfficiencyEta.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/FindingLeadingChargeHadronEfficiencyPhi.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/FindingLeadingChargeHadronEfficiencyPhi.png" width="290" border="0" alt="FindingLeadingChargeHadronEfficiencyPhi.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/FindingLeadingChargeHadronEfficiencyPt.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/FindingLeadingChargeHadronEfficiencyPt.png" width="290" border="0" alt="FindingLeadingChargeHadronEfficiencyPt.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/FindingLeadingChargeHadronEfficiencyEnergy.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/FindingLeadingChargeHadronEfficiencyEnergy.png" width="290" border="0" alt="FindingLeadingChargeHadronEfficiencyEnergy.png"></a>\n''')
   outputfile.write('''         </tr>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </tbody>\n''')
   outputfile.write('''         </table>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </div><!-- DIV-4 -->\n''')
   outputfile.write('''         <div></div>\n''')

   outputfile.write('''         <div> <!-- DIV-4 -->\n''')
   outputfile.write('''         <br>\n''')       
   outputfile.write('''         <center><strong>Finding Leading Charged Hadron Partial Efficiency (compared to ''' + comparisonrelease + '''</strong></center>\n''')
   outputfile.write('''         <table border="1" cellpadding="4" align="center">\n''')
   outputfile.write('''         <tbody align="center">\n''')
   outputfile.write('''         <center>\n''')
   outputfile.write('''         <tr>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/FindingLeadingChargedHadronPartialEfficiencyEta.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/FindingLeadingChargedHadronPartialEfficiencyEta.png" width="290" border="0" alt="FindingLeadingChargedHadronPartialEfficiencyEta.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/FindingLeadingChargedHadronPartialEfficiencyPhi.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/FindingLeadingChargedHadronPartialEfficiencyPhi.png" width="290" border="0" alt="FindingLeadingChargedHadronPartialEfficiencyPhi.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/FindingLeadingChargedHadronPartialEfficiencyPt.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/FindingLeadingChargedHadronPartialEfficiencyPt.png" width="290" border="0" alt="FindingLeadingChargedHadronPartialEfficiencyPt.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/FindingLeadingChargedHadronPartialEfficiencyEnergy.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/FindingLeadingChargedHadronPartialEfficiencyEnergy.png" width="290" border="0" alt="FindingLeadingChargedHadronPartialEfficiencyEnergy.png"></a>\n''')
   outputfile.write('''         </tr>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </tbody>\n''')
   outputfile.write('''         </table>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </div><!-- DIV-4 -->\n''')
   outputfile.write('''         <div></div>\n''')   

   outputfile.write('''         <div> <!-- DIV-4 -->\n''')
   outputfile.write('''         <br>\n''')       
   outputfile.write('''         <center><strong>No Charged Hadrons in Isolation annulus Efficiency  (compared to ''' + comparisonrelease + ''')</strong></center>\n''')
   outputfile.write('''         <table border="1" cellpadding="4" align="center">\n''')
   outputfile.write('''         <tbody align="center">\n''')
   outputfile.write('''         <center>\n''')
   outputfile.write('''         <tr>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedHadronsEfficiencyEta.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedHadronsEfficiencyEta.png" width="290" border="0" alt="NoChargedHadronsEfficiencyEta.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedHadronsEfficiencyPhi.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedHadronsEfficiencyPhi.png" width="290" border="0" alt="NoChargedHadronsEfficiencyPhi.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedHadronsEfficiencyPt.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedHadronsEfficiencyPt.png" width="290" border="0" alt="NoChargedHadronsEfficiencyPt.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedHadronsEfficiencyEnergy.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedHadronsEfficiencyEnergy.png" width="290" border="0" alt="NoChargedHadronsEfficiencyEnergy.png"></a>\n''')
   outputfile.write('''         </tr>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </tbody>\n''')
   outputfile.write('''         </table>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </div><!-- DIV-4 -->\n''')
   outputfile.write('''         <div></div>\n''')

   outputfile.write('''         <div> <!-- DIV-4 -->\n''')
   outputfile.write('''         <br>\n''')       
   outputfile.write('''         <center><strong>No Charged Hadrons in Isolation annulus Partial Efficiency  (compared to ''' + comparisonrelease + ''')</strong></center>\n''')
   outputfile.write('''         <table border="1" cellpadding="4" align="center">\n''')
   outputfile.write('''         <tbody align="center">\n''')
   outputfile.write('''         <center>\n''')
   outputfile.write('''         <tr>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedHadronsPartialEfficiencyEta.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedHadronsPartialEfficiencyEta.png" width="290" border="0" alt="NoChargedHadronsPartialEfficiencyEta.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedHadronsPartialEfficiencyPhi.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedHadronsPartialEfficiencyPhi.png" width="290" border="0" alt="NoChargedHadronsPartialEfficiencyPhi.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedHadronsPartialEfficiencyPt.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedHadronsPartialEfficiencyPt.png" width="290" border="0" alt="NoChargedHadronsPartialEfficiencyPt.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedHadronsPartialEfficiencyEnergy.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedHadronsPartialEfficiencyEnergy.png" width="290" border="0" alt="NoChargedHadronsPartialEfficiencyEnergy.png"></a>\n''')
   outputfile.write('''         </tr>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </tbody>\n''')
   outputfile.write('''         </table>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </div><!-- DIV-4 -->\n''')
   outputfile.write('''         <div></div>\n''')

   outputfile.write('''         <div> <!-- DIV-4 -->\n''')
   outputfile.write('''         <br>\n''')       
   outputfile.write('''         <center><strong>No Charged Hadrons and No Gammas Efficiency  (compared to ''' + comparisonrelease + '''</strong></center>\n''')
   outputfile.write('''         <table border="1" cellpadding="4" align="center">\n''')
   outputfile.write('''         <tbody align="center">\n''')
   outputfile.write('''         <center>\n''')
   outputfile.write('''         <tr>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedNoGammasEfficiencyEta.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedNoGammasEfficiencyEta.png" width="290" border="0" alt="NoChargedNoGammasEfficiencyEta.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedNoGammasEfficiencyPhi.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedNoGammasEfficiencyPhi.png" width="290" border="0" alt="NoChargedNoGammasEfficiencyPhi.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedNoGammasEfficiencyPt.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedNoGammasEfficiencyPt.png" width="290" border="0" alt="NoChargedNoGammasEfficiencyPt.png"></a>\n''')
   outputfile.write('''         <td><a href="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedNoGammasEfficiencyEnergy.png">\n''')
   outputfile.write('''            <img src="''' + tagtype + '''/''' + prongsanalyzed +'''/NoChargedNoGammasEfficiencyEnergy.png" width="290" border="0" alt="NoChargedNoGammasEfficiencyEnergy.png"></a>\n''')
   outputfile.write('''         </tr>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </tbody>\n''')
   outputfile.write('''         </table>\n''')
   outputfile.write('''         </center>\n''')
   outputfile.write('''         </div><!-- DIV-4 -->\n''')
   outputfile.write('''         <div></div>\n''')
   
   outputfile.write('''     </div> <!-- DIV-3 -->\n''')   
   
   outputfile.write('''</div> <!-- DIV-2 -->\n''')
   outputfile.write('''<div class="fedora-coner-br">&nbsp;</div>\n''')
   outputfile.write('''<div class="fedora-coner-bl">&nbsp;</div>\n''')
   outputfile.write('''<!-- content END -->\n\n''')
   outputfile.write('''<!-- footer BEGIN -->\n''')
   outputfile.write('''<div id="fedora-footer">\n''')
   outputfile.write('''Ricardo Vasquez Sierra\n''')
   outputfile.write('''<br>\n''')
   outputfile.write('''Fermilab/UCDavis\n''')
   outputfile.write('''<br>\n''')
   outputfile.write('''</div>\n''')
   outputfile.write('''<!-- footer END -->\n''')
   outputfile.write('''</body></html>\n''')
